language: go
os: linux
arch: ppc64le
dist: bionic
go: 
  - "1.13.4"
  #- "1.11.7"
  #- "1.11.1"

install:
  - GO111MODULE=off go get golang.org/x/lint/golint
  - sudo apt update
  - sudo apt install -y lftp unzip zip build-essential tar wget

script:
  - bash build.sh
