language: go
os: linux
arch: ppc64le
dist: bionic
services:
  - docker
go: "1.14.x"

install:
  - GO111MODULE=off go get golang.org/x/lint/golint
  - sudo apt update
  - sudo apt install -y lftp unzip zip build-essential tar wget

script:
  - bash build.sh
